Fixed: Missing case for datatype
Previously the docs build would fail with an error:

ERROR: Cannot resolve the following datatype:
            <rng:param name="minInclusive">2</rng:param>

This commit fixes this error by adding a new case for positiveIntegers and minInclusive.